name: water_bottle
description: This library add a bottle/flask widget to your screen. You can use it as a loading indicator, a progress tracker, or any kind of measurement suits your needs.
homepage: https://github.com/zonaro/water_bottle

version: 0.0.8

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_parsing: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
